### ISSUE TITLE
There is no way to change the position of a post in the page

### ISSUE THREAD

**Issue by skydread1** [skydread1/flybot.sg#169]
## Problem

As for now, we have options to order the post per page using their creation/last-edition date in (reverse) chronological order.

However, there is no way to have a custom order of posts which could be very convenient for the page `home`, `apply` and `about`.

## Suggestion

- add a `:post/order` field for a post in the datalevin schema
- take care of validation schema update
- take care of incrementing by one the other posts of the page coming after the insertion post

**Comment by flybot-nam-nguyenhoai** [comment]
Another possible approach is to attach a default post order to each page. Post orders can be directly represented as vectors of unique UUIDs, which should make it easier to query and update them.
    
(Optional) If the `:post/page` field is also removed for posts, then the same post can even be included in multiple pages.

**Comment by flybot-nam-nguyenhoai** [comment]
I'll try the first approach (`:post/order` for each post) first.
