### ISSUE TITLE
There is no backend for data persistence

### ISSUE THREAD

**Issue by skydread1** [skydread1/flybot.sg#42]
## Problem

In theory, a SPA is fine for our need as we just deliver static content.

However, as part of our work on our open-source [lasagna](https://github.com/flybot-sg) stack (fun-map, pull and remote-pull),
we want to use our website as an example of the good use case of our stack.

So, for a pull api and map value accessing demo to make sense, we need an actual backend.

## Suggestion

- backend in Clojure
- Use aleph/ring for http
- Use xtdb as datalog DB

**Comment by robertluo** [comment]
[datalevin](https://github.com/juji-io/datalevin) looks promising and should be much easier to get start with.

**Comment by skydread1** [comment]
Ok, noted!
